version: '3.9'
services:
  mysql:
    image: mysql:5.6
    container_name: ipam-database
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin

  ipam:
    image: pierrecdn/phpipam
    container_name: ipam-web
    restart: always
    depends_on:
      - mysql
    ports:
      - "8010:80"
      - "8011:443"
    environment:
      - MYSQL_ENV_MYSQL_USER=root
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=admin
      - MYSQL_ENV_MYSQL_HOST=mysql

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local