version: '3.9'
services:
  mysql:
    image: mysql:5.6
    container_name: ipam-database
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}

  ipam:
    image: pierrecdn/phpipam
    container_name: ipam-web
    restart: always
    depends_on:
      - mysql
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    environment:
      - MYSQL_ENV_MYSQL_USER=${DB_USER}
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_ENV_MYSQL_HOST=mysql

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
