version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: ipam-database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=phpipam

  web:
    image: pierrecdn/phpipam
    container_name: ipam-web
    restart: always
    depends_on:
      - db
    ports:
      - "8010:80"
      - "8011:443"
    environment:
      - MYSQL_ENV_MYSQL_USER=root
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=phpipam
      - MYSQL_ENV_MYSQL_HOST=mysql

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
